services:
  frontend:
    build:
      context: ./frontend   # Path to your frontend folder
      dockerfile: Dockerfile
    ports:
      - "80:80"         # Host:Container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.env      # Load env variables from file
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
